// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var IndexGen = require("./index.gen");

function createGreeting(prim) {
  return IndexGen.createGreeting(prim);
}

console.log(IndexGen.createGreeting("it works"));

exports.createGreeting = createGreeting;
/*  Not a pure module */
